enum AuthNotification {
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  ACCOUNT_VERIFICATION_LETTER_SENT = 'ACCOUNT_VERIFICATION_LETTER_SENT',
  ACCOUNT_VERIFICATION_SUCCESS = 'ACCOUNT_VERIFICATION_SUCCESS',
}

export { AuthNotification };
