version: '3'
services:
  backend:
    image: backend
    build:
      context: .docker
      dockerfile: .docker/backend.Dockerfile
    container_name: backend
    ports:
      - '5001:5001'
    env_file:
      - ../.env/api.env
    networks:
      - backend-network
      - frontend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  frontend:
    image: frontend
    build:
      context: .docker
      dockerfile: .docker/backend.Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - '8080:80'
      - '443:443'
    env_file:
      - ../.env/client.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ../nginx/nginx.local.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network
      - frontend-network

volumes:
  shared:
    driver: local

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge