name: Deploy to heroku.

on:
  push:
    branches: [master]

jobs:
  prepareEnviroment: 
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
  deploy-frontend:
    needs: prepareEnviroment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release an app frotnend to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: frontend.Dockerfile
          docker_options: "--no-cache"
          process_type: web
  deploy-backend:
    needs: [prepareEnviroment, deploy-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release an app backend to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: backend.Dockerfile
          docker_options: "--no-cache  --build-arg REACT_APP_API_ORIGIN_URL=/api/v1 --build-arg REACT_APP_SERVER_HOST=https://dragon-space-app-backend.herokuapp.com/"
          process_type: web
    
