name: Deploy to heroku.

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: node-version:16
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
        - run:npm install
  lint:
    runs-on: node-version:16
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
        - run:npm run lint
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: frontend.Dockerfile
          docker_options: "--no-cache"
          process_type: web
          
