name: Deploy to heroku.

on:
  push:
    branches: [master]

jobs:
  prepareEnviroment: 
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
  deploy-frontend:
    needs: prepareEnviroment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release an app frotnend to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: frontend.Dockerfile
          docker_options: "--no-cache --build-arg REACT_APP_API_ORIGIN_URL=${{ secrets.REACT_APP_API_ORIGIN_URL }} --build-arg REACT_APP_SERVER_HOST=${{ secrets.REACT_APP_SERVER_HOST }}"
          process_type: web
  deploy-backend:
    needs: [prepareEnviroment, deploy-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release an app backend to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: backend.Dockerfile
          docker_options: "--no-cache"
          process_type: web
  deploy-test:
      needs: [deploy-backend]
      name: run tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: cd tests
        - run: touch .env
        - run: ls -a
        - run: echo "TESTS_ENV_NAME=Environment" >> .env
        - run: echo "TESTS_BASE_URL=${{ secrets.TESTS_BASE_URL }}" >> .env
        - run: echo "TESTS_SWAGGER_URL=${{ secrets.TESTS_SWAGGER_URL }}" >> .env
        - run: echo "TESTS_USER_EMAIL=${{ secrets.TESTS_USER_EMAIL }}" >> .env
        - run: echo "TESTS_USER_PASSWORD=${{ secrets.TESTS_USER_PASSWORD }}" >> .env
        - run: npm i
        - run: npm run test
